# Generated by Django 4.1.1 on 2022-09-13 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 13, 6, 15, 50, 856668, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="end date",
            ),
        ),
    ]
