# Generated by Django 4.1.1 on 2022-09-20 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_question_previous_vote_alter_question_end_date_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 20, 9, 59, 35, 179199, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="end date",
            ),
        ),
    ]
